Feature/credit #25
Yamato-Security/RustyBlue pull request #34
Opened 2021-07-18 05:17 UTC by ichiichi11

2021-07-19 00:16 UTC, hitenkoku requested changes
確認しました。2名入っていない方がいるようなので別途連絡いたします。

2021-07-19 00:16 UTC, hitenkoku commented on credits.txt
> +dai (twitter: @@__da13__) Developer
@が重複しているので削除をお願いします

2021-07-19 00:16 UTC, hitenkoku commented on credits.txt
> +mimura (twitter: @@mimura1133) Developer
@が重複しているので削除をお願いします

2021-07-19 11:03 UTC, ichiichi11 commented on credits.txt
> +dai (twitter: @@__da13__) Developer
直しました

2021-07-19 11:04 UTC, ichiichi11 commented
@hitenkoku 多分、全部直ったと思います。

2021-07-19 23:44 UTC, hitenkoku approved these changes
修正対応ありがとうございました。確認しました。問題ありません。

2021-07-20 09:17 UTC, ichiichi11 commented
既に別のbranchでまとめてマージしたので、このプルリクエストはcloseします。

2021-07-20 09:17 UTC, closed without merging